### PR TITLE
Add .swagger-codegen-ignore support

### PR DESCRIPTION
**Pull request by jimschubert**
Code generated with Swagger Codegen includes a `.swagger-codegen-ignore` file in the project's root. I've been assigning it manually as a file pattern to the git ignore file type, but it'd be nice to have it by default with the .ignore plugin.

I bumped the version number in `gradle.properties` and `resources/META-INF/plugin.xml`. If that's not appropriate, let me know and I'll remove that change.

### CODE REVIEW

**Comment by hsz** [comment]
@jimschubert Thank you for this PR! Everything is done correctly, I'll include your change in the next v2.0.0 release.

**Comment by hsz** [comment]
@jimschubert Just for the future: regular icons have `#383838` color, and `_dark` ones: `#c8c8c8`.

You have missed `icon_swagger-codegen_dark.png` asset - it causes displaying dark icon in dark IDE, so it's not visible.
But don't worry, I'll correct everything.

**Comment by jimschubert** [comment]
@hsz weird I created the dark icon, I used a picker for the colors so they're probably off by a bit. I must have the icon excluded by a global ignore rule or something.

I have the svg I created for the icon. I can share that later if you'd like.

**Comment by hsz** [comment]
@jimschubert It's fine - I just did it. That wasn't a problem at all.

**Comment by jimschubert** [comment]
Awesome! Thank you.

**Pull request merged**
